id: P3BBE5D49
initial_creation_type: input
source_metadata:
  title: Sakya Paṇḍita Series
  language: es
  description: 'A series of texts by and about the great scholar Sakya Paṇḍita Kunga
    Gyaltsen (kun dga'' rgyal mtshan, 1182–1251):'
  volume:
    31624c7086594a1abeb778e0d3ed0d39:
      title: A Wondrous Instruction for the Moment of Death
      parent: Advice
    8af3adc87fd848e8b29cf71fa0f59dfb:
      title: Meditation on Amitābha
      parent: Advice
    3b480e56d6b64293b0bc176a9749ee6d:
      title: Verses of Aspiration to Recite While Prostrating
      parent: Aspiration Prayers
    83b31a77673a4a07ba9750bd78d17f67:
      title: The Gaṇacakra Ritual
      parent: Commentaries
    d03e576dbc984a4081a0b6c5a5240e61:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Guru Yoga
    76f7d0fb022e4820b3735665021ba0ee:
      title: 'The Sun of Ambrosial Wisdom: A Guru Yoga of Dharmarāja Sakya Paṇḍita'
      parent: Guru Yoga
    42717475e0a5476f9c11bd922281ae14:
      title: Sakya Paṇḍita’s Instruction on Parting from the Four Attachments
      parent: Mind Training
    b92f72a576a142459077500f766436e2:
      title: Praise to Sakya Paṇḍita
      parent: Praise
    d2b2c9d2798b4911ad06aabc697e998a:
      title: Prayer to Invoke the Wisdom Mind of the Gentle Protector Sakya Paṇḍita
      parent: Prayers
created_at: '2022-03-01T01:26:41.730957'
last_modified_at: '2022-03-01T01:26:41.730960'
